name: Update Prettier
"on":
  push:
    branches:
      - renovate/prettier-*
jobs:
  update_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run lint:fix
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOKITBOT_PAT }}
        with:
          title: Prettier updated
          body: An update to prettier required updates to your code.
          branch: ${{ github.ref }}
          commit-message: "style: prettier"
